### ISSUE TITLE
Using in project subfolders

### ISSUE THREAD

**Issue by jdosullivan** [KSubedi/net-core-project-manager#1]
Tried to use it in subfolders containing projects and it through a "Could not find project.json" error. Just in case anyone is running into similar issues.

The extension expects the project.json to be in the root folder so to use it in a subfolder open the subfolder by itself in a new window of vscode.

**Comment by KSubedi** [comment]
Thank you for bringing this to attention. I will try to find a way to make the location of project.json configurable.
